import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head />
      <body>
        <nav>
          <Link href="/">HOME</Link> &nbsp;
          <Link href="/posts">POST</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
